### 📝 Registro de usuario
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "juan",
    "password": "mi_secreto_123"
}

###

### 🔑 Login de usuario
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "juan",
    "password": "mi_secreto_123"
}

###

### 🔒 Endpoint protegido de prueba (ejemplo)
GET http://localhost:8000/api/capsules/
Authorization: Token {{token}}
Accept: application/json