# Generated by Django 5.2 on 2025-08-23 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='capsule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CapsuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='capsules.capsule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('capsule', 'user')},
            },
        ),
    ]
